export enum AuthRepositoryEnum {
  USER_REPOSITORY = 'USER_REPOSITORY',
  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  TRANSACTIONAL_CODE_REPOSITORY = 'TRANSACTIONAL_CODE_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
} 