export enum AuthRepositoryEnum {
  AUDIT_REPOSITORY = 'AUDIT_REPOSITORY',
  MENU_REPOSITORY = 'MENU_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  TRANSACTIONAL_CODE_REPOSITORY = 'TRANSACTIONAL_CODE_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
}

export enum CommonRepositoryEnum {
  FILE_REPOSITORY = 'FILE_REPOSITORY',
  CATALOGUE_REPOSITORY='CATALOGUE_REPOSITORY'
}

export enum CoreRepositoryEnum {
  ATTENDANCE_REPOSITORY = 'ATTENDANCE_REPOSITORY',
  EMPLOYEE_REPOSITORY = 'EMPLOYEE_REPOSITORY',
  SCHEDULE_REPOSITORY = 'SCHEDULE_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  PERMISSION_TYPE_REPOSITORY = 'PERMISSION_TYPE_REPOSITORY',
  VACATION_REPOSITORY = 'VACATION_REPOSITORY',
  FORM_REPOSITORY = 'FORM_REPOSITORY',
  VACATION_DETAIL_REPOSITORY = 'VACATION_DETAIL_REPOSITORY',
  PERMISSION_STATE_REPOSITORY = 'PERMISSION_STATE_REPOSITORY',
  SIGNER_REPOSITORY = 'SIGNER_REPOSITORY',
  SITE_REPOSITORY = 'SITE_REPOSITORY',
}
